[package]
name = "mdcr-test-scrape"
version = "1.0.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
csv = "1.3.0"
html_parser = "0.7.0"
reqwest = { version = "0.11.24", features = ["blocking"] }
scraper = "0.19.0"
serde = { version = "1.0.197", features = ["derive"] }
